## Install and trigger Pelican publish
name: Trigger Make

on:
  push:
    branches: [ dev ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pelican
        
        python -m pip install "pelican[markdown]"
        #
        git clone https://github.com/alexandrevicenzi/Flex
        pelican-themes --install Flex/ --verbose
        pelican-themes -l
                
    - name: Generate OutPutfolder
      run: |
        echo $BUCKET_NAME
        make publish
    - name: Upload outputfolder 
      uses: actions/upload-artifact@master
      with:
        name: outputfolder
        path: ./output/
  upload:
    name: Upload assets to S3 bucket
    permissions:
      id-token: write # This is required for requesting the JWT
    needs: [deploy]
    runs-on: ubuntu-latest
    environment:
      name: mine
    steps:
    - uses: actions/download-artifact@master
      with:
        name: outputfolder
        path: ./output/
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region:  ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: AssetsUploadSession
    - name: Copy files to S3 bucket
      run: |
        ls
        aws s3 sync output/ s3://${{ secrets.BUCKET_NAME }}
