## Install and trigger Pelican publish
name: Trigger Make

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pelican
        pelican --help
        pelican-themes ls
        python -m pip install "pelican[markdown]"
        echo $PWD
        cd $PYTHON_HOME
        mkdir pelican-addon-clones
        cd pelican-addon-clones
        git clone https://github.com/alexandrevicenzi/Flex
        pelican-themes --install Flex/ --verbose
        pican-themes --list
                
    - name: Generate OutPutfolder
      run: |
        make publish
